app:
  url: 'http://localhost:6600'
routes:
  config:           '/api/config'
  projects:         '/api/projects'
  build-project:    '/api/build'
  builds:           '/api/builds'
  build:            '/api/builds/:build'
  github-hooks:     '/public/api/hooks/github'